name: dune-fem tutorial

on: [pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          bash ./ossetup "$RUNNER_OS"
          pip install sphinx sphinxcontrib-bibtex sphinx-versioning sphinxcontrib-packages nbsphinx sphinx_rtd_theme myst_parser numpy>=1.20 scipy nbconvert ipython jupyter jupytext pandas matplotlib pandoc pyqt5 sphinx-autobuild sphinx_rtd_theme sphinxcontrib-bibtex sortedcontainers triangle fenics-ufl==2024.2.0 x3d pygmsh

      - name: Sphinx build
        run: |
          sphinx-build doc versions/v2.11.0.3
          ln -s versions/v2.11.0.3/* versions 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: versions/
          force_orphan: true

