name: dune-fem tutorial

on: 
  workflow_dispatch:
    branches:
      - main
    inputs: 
      version:
        # note: this should be either 'latest' or a tag of the dune-fem tutorial version
        #       vN where 'N' is a legal python package version e.g. N=2.11.0.3
        type: string
        description: 'tutorial version tag e.g. (latest | v2.11.0.3) [latest]'
        required: true
        default: 'latest'
      keepfiles:
        type: boolean
        description: keep older versions [true]
        required: true
        default: true
      deploy:
        type: boolean
        description: deploy web pages [true]
        required: true
        default: true
      # needed only for dispatching from other repo
      distinct_id:
        required: false
        description: 'set when dispatching from external repo - leave empty'

permissions:
  contents: write

jobs:
  builddocu:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        if: github.event.inputs.distinct_id != ''
        run: echo ${{ github.event.inputs.distinct_id }}
      # check documentation from version branch
      - uses: actions/checkout@v4
      #  with:
      #    ref: ${{ github.event.inputs.version }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14
      # install packages
      - name: Install dependencies
        run: |
          sudo apt-get update -o Acquire::Retries=3
          sudo apt-get install python3-numpy python3-matplotlib python3-scipy python3-ufl pandoc
          pip install sphinx sphinxcontrib-bibtex sphinx-versioning sphinxcontrib-packages nbsphinx sphinx_rtd_theme myst_parser numpy>=1.20 scipy nbconvert ipython jupyter jupytext pandas matplotlib pandoc pyqt5 sphinx-autobuild sphinx_rtd_theme sphinxcontrib-bibtex
      # build sphinx documentation
      # the documentation will be placed in versions/v.x.x.x.x
      # versions/index.html is a redirection to the latest fem version directory
      - name: checkout
        run: |
          git clone -b gh-pages https://github.com/${{ github.repository }}
          echo "TUTORIAL=tutorial" >> $GITHUB_ENV
          
      - name: latest2branch
        if: github.event.inputs.version == 'latest'
        run: |
          cd ${{ github.event.repository.name }}
          BRANCH=`git branch -r | grep "$TUTORIAL/" | sort -rn | head -1 | cut -d "/" -f 3`
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "Using branch $BRANCH"
          cd ../
      - name: version2branch 
        if: github.event.inputs.version != 'latest'
        run: echo "BRANCH=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Sphinx build
        run: |
          echo "Building documentation for $BRANCH"

          # find other versions
          echo $BRANCH > latest.txt
          cd ${{ github.event.repository.name }}
          ls -dvr v* >> ../latest.txt
          # cleanup 
          cd ..
          rm -rf ${{ github.event.repository.name }}

          # make versions unique 
          sort -nr latest.txt | uniq > uniqsorted.txt

          # get latest version tag
          LATEST=`head -1 uniqsorted.txt`

          # get tutorial source to build web page
          git clone -b $TUTORIAL/$BRANCH https://github.com/${{ github.repository }}
          
          # create versions.rst
          bash createversions.sh < uniqsorted.txt
          mv versions.rst ${{ github.event.repository.name }}/doc

          # build docu
          sphinx-build ${{ github.event.repository.name }}/doc versions/$BRANCH

          echo "Setting link to latest documentation for $LATEST"
          # write redirect index.html
          echo "<meta http-equiv=\"refresh\" content=\"0; url=https://dune-project.github.io/dune-fem-tutorial/$LATEST\" />" > versions/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        # only deploying on main branch
        if: ${{ github.event.inputs.deploy && github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: versions/
          # keep files to keep previous documentations
          keep_files: ${{ github.event.inputs.keepfiles }}
          #force_orphan: true

